<template>
  <LandingPageNavigationComponent :scrolled="scrolled"/>
  <HomeSection />
  <AboutSection />
  
<!-- 
  <div class="content-landing pt-16">
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci reiciendis minus quo libero minima vel eligendi inventore harum neque possimus placeat porro earum quod maiores ipsum, suscipit consequatur nulla nisi tenetur obcaecati sit quaerat praesentium! Ipsam at quia maiores soluta eius facilis nesciunt quod tempore labore. Debitis omnis rem obcaecati, nihil dignissimos voluptatem architecto neque deserunt quasi voluptate consequatur maxime est aspernatur! Voluptas temporibus ipsum dolores laborum laboriosam dignissimos ad earum distinctio, nemo doloribus! Aperiam quo iste saepe ex necessitatibus vel repellendus ipsum sit exercitationem! Harum provident rem vitae repellat quis quidem commodi odio, a culpa quod praesentium nemo adipisci numquam dicta molestias, alias deleniti amet fugit! Placeat quam consequuntur praesentium dignissimos? Veritatis molestiae soluta ullam animi quam dolores itaque vel! Consequatur, necessitatibus? Voluptatum esse libero expedita tempora ea, reiciendis maxime modi numquam voluptatibus quo sit consectetur error delectus consequatur rerum laudantium pariatur quae voluptatem harum est odit quibusdam eum tempore laborum. Ullam minima tempora possimus officia! Deleniti est officiis quibusdam nemo obcaecati, hic quae reiciendis illo sint, omnis, laborum iure placeat laboriosam eos blanditiis unde minima quas. Minima, obcaecati quis culpa distinctio nulla nihil natus tempore. Tempore sunt deleniti in nesciunt architecto nostrum corporis, laboriosam officia saepe labore velit sit ea maiores totam inventore dolorem ullam ad sed asperiores distinctio nulla doloribus! Obcaecati fugiat repellat odit perspiciatis error, tempora saepe alias, distinctio explicabo, corporis nisi magnam quidem quae unde aspernatur voluptas voluptatum eaque ab commodi. Inventore porro hic maiores voluptas dicta, amet a dolore nulla aliquid sed quos quia optio voluptatum tempora odit veritatis deserunt temporibus omnis! Culpa optio harum error impedit pariatur doloribus tenetur maiores fugiat, esse provident, nihil doloremque perspiciatis nobis similique laudantium quae enim ex. Error possimus quidem aliquid voluptatem officia suscipit, ducimus cupiditate recusandae placeat, perspiciatis hic cumque voluptatum tempora. Magnam aspernatur quibusdam vitae optio.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil incidunt similique perspiciatis esse, labore odit perferendis, quam itaque vitae saepe vero aliquid ducimus veniam assumenda earum aspernatur voluptatem voluptas a dolor cupiditate id? Quis magnam temporibus illum quasi. Autem id aliquid possimus harum dignissimos facilis ipsa, obcaecati aliquam officia. Expedita aut ex odit rerum nihil, eaque repellendus omnis adipisci eveniet neque sunt quod veniam. Doloribus asperiores dignissimos consequuntur labore, veniam voluptatum in facilis deleniti dolore, dolorem aliquam, numquam qui? Quod cupiditate distinctio veritatis? Consequuntur ducimus dignissimos perspiciatis nulla id dolore maiores deleniti recusandae exercitationem tempore sed nisi vero laborum, deserunt repellat sapiente illo quos vel distinctio ipsum officiis vitae nobis ipsa? At corporis dolorum velit, itaque nam dicta doloremque, mollitia quia nulla ullam praesentium dignissimos temporibus. Vitae ratione eaque, quisquam, sit placeat veritatis animi nemo reiciendis iste ab non corporis, praesentium quas? Molestias inventore exercitationem, eius blanditiis animi impedit reiciendis cupiditate. Aliquam dolorum animi labore sapiente facilis, id delectus, corrupti officiis blanditiis necessitatibus assumenda ab aliquid. Ex nobis doloribus cumque, odit ad velit rem delectus, aspernatur, eos maiores natus magnam et dolores omnis. Dolor deleniti, molestiae possimus magnam reprehenderit cupiditate quisquam voluptatem, eos reiciendis aliquid in quis laborum saepe, nam odio hic nobis nostrum placeat porro autem ducimus! Fugiat odit assumenda consectetur earum voluptate fuga provident? Nihil enim temporibus doloremque! Quos, voluptatibus tempore explicabo corrupti pariatur natus, nihil beatae quasi provident quisquam dolorem quas sint aspernatur totam impedit architecto aliquam quam? Debitis nobis exercitationem, ducimus et explicabo soluta ratione reprehenderit. In similique at quaerat architecto ratione? Veniam, neque ad. Accusamus laborum voluptas vitae enim quisquam quas amet esse nobis, facere quia magni veniam perferendis ullam consequuntur id eos cumque blanditiis eveniet officia mollitia vero quis fugiat! Magnam voluptatem optio molestias doloremque sunt excepturi, esse labore delectus ut nisi, mollitia ipsam?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, quisquam illo, adipisci delectus illum dolorem eius porro ratione possimus quos, eaque repudiandae optio aut voluptates aspernatur aperiam dignissimos facilis ipsam obcaecati molestiae earum consequuntur iusto eveniet. Debitis impedit dolor omnis sunt rerum, eveniet quas vel blanditiis voluptatum, quod voluptas enim illo rem mollitia magnam maxime cumque adipisci laborum sint esse similique molestiae iste sit! Officia numquam, labore excepturi dolor fuga soluta voluptates. Libero quaerat placeat quas provident excepturi repellat corporis labore doloribus aut sed quisquam, laborum iste quod, esse temporibus id ab doloremque. Autem, sint non perferendis numquam esse fugiat quia doloremque vero qui quo cum incidunt ea? Quisquam maiores fuga sunt exercitationem labore in libero, accusantium tempora at earum dolore, illum eligendi similique expedita a sequi quae minima ab laudantium mollitia. Ex minus est veniam earum eveniet quis magnam impedit beatae dolor fuga aliquam, dicta itaque laudantium id illo esse voluptatem! Fugiat sed, amet iste dolores placeat harum temporibus minus molestias, dolor, voluptatem incidunt dolorem architecto. Quibusdam animi necessitatibus maxime aut, pariatur possimus, magnam nisi nesciunt porro recusandae numquam inventore illo est saepe ratione officia nulla optio, itaque fugit? Iure voluptatum architecto mollitia tempora provident hic id corrupti nam sed quae deserunt adipisci, cupiditate dolores rerum nisi quos est itaque soluta totam libero nostrum. Earum, maxime cum totam magnam saepe voluptate dignissimos commodi dolores, sapiente officia reiciendis deserunt officiis, cupiditate suscipit distinctio facere cumque corporis repellendus. Cumque quidem consequatur vitae ut quae adipisci ad obcaecati, accusantium neque, modi nam deserunt consectetur, reiciendis reprehenderit voluptatibus voluptate aliquam eaque sit. Dolorum fugit ut, tempore corporis dicta autem recusandae error reiciendis atque distinctio vitae accusantium facere itaque cum eius eveniet vel dolore adipisci molestias officia debitis molestiae. Dicta repellendus doloremque fuga asperiores accusantium explicabo ex soluta, tempora autem, ut optio nesciunt animi.
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat asperiores perferendis maiores doloribus molestiae placeat neque quis explicabo magni quidem quasi reiciendis, doloremque amet, facere quo. Neque similique eveniet ad quasi quaerat corrupti modi quis delectus repellat fugit dolores, non deleniti tempore iste rem amet dolorum. Fuga id veritatis est nesciunt dolorem animi architecto ea itaque perspiciatis laborum saepe possimus ducimus esse rerum eum ut pariatur ipsam laudantium, minima maxime, qui consequatur! Laboriosam atque nulla dignissimos architecto, praesentium illo sit mollitia quas fugit vero quasi rem, nam et? Nihil aut praesentium assumenda voluptatum saepe illum deserunt mollitia corporis obcaecati ratione quo quaerat eligendi hic, quas ullam quos expedita molestiae reprehenderit quisquam porro minus quae. Expedita praesentium aliquam ex nesciunt doloribus reiciendis? Labore illum quidem quod iusto! Doloremque ipsa velit aliquam facere dolorum illum beatae iste iure dolores, animi voluptas consequuntur aut soluta sapiente libero itaque. Quisquam iusto nulla in pariatur voluptatibus maxime cumque velit deserunt aliquid, earum voluptatum sapiente magnam nihil veritatis dignissimos exercitationem, nostrum sunt, autem delectus accusamus harum quam. Sunt voluptas obcaecati repudiandae ullam totam, corporis blanditiis hic, voluptates, recusandae molestias at suscipit repellendus tenetur inventore cum. Dolor ex debitis iste quod quasi facilis. Beatae esse aliquam id, commodi modi cupiditate veniam, ipsa eos voluptatum nisi quaerat. In minus laboriosam nesciunt magnam, modi nobis ea soluta assumenda voluptate consequatur, aliquid dolorem repellat. Aut fuga rerum velit rem? Deleniti expedita doloribus doloremque, fugiat nulla, vel, iste debitis neque vitae excepturi quae soluta explicabo quis rem tempora autem quod dolore quia? Sed obcaecati hic laudantium illo nihil provident, eius numquam reiciendis facere quisquam dicta accusamus possimus tempore vel officiis, nulla doloribus minima! Minima dolorem at iusto reprehenderit nulla aspernatur molestiae voluptatem repellat. Pariatur incidunt perferendis magni natus, debitis quas iusto blanditiis dolore tenetur ab fuga explicabo, deleniti ipsam velit in.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem molestiae facere enim in sed deserunt consequatur, repellendus maxime accusamus. Nam perferendis laboriosam vitae! Earum cum laudantium accusamus ipsam rerum? Eum minus praesentium possimus blanditiis ad numquam suscipit, corporis recusandae, maxime molestiae fugit atque veniam. Eos voluptatibus eligendi sequi tenetur molestias? Rem ut voluptatem pariatur, deleniti id quo consectetur odio voluptas ea doloremque nisi, dolorum sint quidem exercitationem obcaecati totam perferendis autem repudiandae, suscipit iusto commodi ad nemo dignissimos. Officia necessitatibus reprehenderit facilis nam, ducimus non dolores, ad enim, iure eos dicta. Non recusandae aliquid odio minima, in quasi distinctio laboriosam qui doloribus nisi quam dolorem? Rerum nulla quas numquam. Repellendus corporis explicabo nihil nam asperiores consequatur nobis. Illum quia voluptas assumenda quasi nostrum dolorem deleniti accusantium aliquid, sequi consequatur voluptatibus architecto minima impedit odio voluptatum quibusdam, accusamus tenetur repudiandae optio, provident et! Dolorum voluptates, corporis harum error odio sunt veniam nulla accusantium impedit magnam rem, hic quaerat? Sit omnis quis dignissimos voluptates magni optio itaque, nisi provident vel repellat expedita necessitatibus molestias commodi voluptatem pariatur assumenda ad architecto ut, praesentium perspiciatis. Soluta, non nihil nemo consequuntur corporis iusto rem fuga, culpa est enim consequatur iste tenetur, aspernatur incidunt esse. Harum cumque temporibus suscipit assumenda nihil aliquam accusantium sed corporis tempore laborum excepturi dolore ipsa, quis sit rerum itaque velit. Aliquid eos atque molestiae soluta consequatur esse fugit praesentium molestias magnam sequi nam quia ipsa ducimus commodi sapiente, culpa, natus, sint ullam? Quos obcaecati, impedit iure possimus reprehenderit praesentium, exercitationem, facilis est debitis laboriosam harum repudiandae quibusdam error animi? Minima, iusto dolorum earum qui, fugit minus temporibus sequi maxime ullam eveniet voluptatem reprehenderit mollitia quas ut necessitatibus accusamus obcaecati nobis consequuntur rem exercitationem quis alias quidem voluptas. Iusto numquam excepturi ipsam reprehenderit velit, esse illum quis eligendi quam, beatae exercitationem expedita.

  </div> -->
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';

import LandingPageNavigationComponent from '@/components/LandingPage/LandingPageNavigationComponent.vue';
import HomeSection from '@/components/LandingPage/HomeSection.vue';
import AboutSection from '@/components/LandingPage/AboutSection.vue';

const scrolled = ref(false)

onMounted( () => {
  window.onscroll = () => scrolled.value = document.documentElement.scrollTop > 0;
});


</script>


<style>


</style>

